src/components/icon-modals/iconModals.styled.tsx, src/components/login/login-form/index.tsx, src/components/login/login-form/loginForm.styled.tsx
✓Removing console logs
✓Ordering imports
✓Defining params structure
✓Removing type any with proper type
✓Removing inline styles
✓Responsiveness check
✓Proper folder and file structure
✓Defining constants for lengthy conditions
✓Use proper ternary instead of using if else
Declaring proper initial value to both local and global states
✓Should clean side-effects on component unmounting
✓Clear warnings and errors (rendered on browser’s console)
✓Remove unused imports and variables
✓Follow SOLID principles
✓Declare reusable components
✓Put meaningful commit message (Sentence should start with capital letter and end with dot)
✓Pull before every push
Paste checked conditions of above in pull/push request description
Raise …
=> Adding full width style to text field.

src/components/rich-text/rich-text-menu-bar/menuBar.tsx
✅Removing console logs
✅Ordering imports
✅Defining params structure
✅Removing type any with proper type
✅Removing inline styles
✅Responsiveness check
✅Prettier usage
✅Proper folder and file structure
✅Defining constants for lengthy conditions
✅Use proper ternary instead of using if else
✅Declaring proper initial value to both local and global states
✅Should clean side-effects on component unmounting
✅Clear warnings and errors (rendered on browser’s console)
✅Remove unused imports and variables
✅Follow SOLID principles
✅Declare reusable components
✅Put meaningful commit message (Sentence should start with capital letter and end with dot)
✅Pull before every push
✅Paste checked conditions of above in pull/push request description
✅Raise …
=> Replaced type in rich text editor file.

src/components/tables/farmers-details-table/body/body.styled.tsx, src/components/tables/farmers-details-table/body/index.tsx, src/components/tables/farmers-group-table/body/body.styled.tsx, src/components/tables/farmers-group-table/body/index.tsx, src/components/tables/md-details-table/body/body.styled.tsx, src/components/tables/md-details-table/body/index.tsx
Use proper ternary instead of using if else
Follow SOLID principles …
=> Resolve Table Search No data message not shown issue.

src/components/decisions/decisions-header/index.tsx, src/components/input-fields/dateTime/dateTime.styled.tsx, src/components/input-fields/dateTime/index.tsx, src/components/input-fields/radio/index.tsx, src/components/modals/decisions-modal/body/formField.tsx, src/components/modals/decisions-modal/index.tsx, src/components/modals/type/formInputs.ts, src/utils/constants/index.ts
=> Added time field & implemented conditional group selection in decisions modal.

src/components/rich-text/richText.styled.tsx, src/containers/layout/Layout.tsx
=> Rich text auto-submission bug fixed.

src/views/ceo-details/ceo-details.styled.tsx
=> UI issue of cards alignment updated in ceo details page.

src/components/common-components/select-dropdown/index.tsx, src/components/custom-tables/footer/index.tsx, src/components/modals/farmers-group-modal/index.tsx, src/components/tables/farmers-details-table/body/index.tsx, src/components/tables/farmers-details-table/footer/index.tsx, src/components/tables/farmers-group-table/body/index.tsx, src/components/tables/farmers-group-table/footer/index.tsx, src/components/tables/founders-table/body/index.tsx, src/components/tables/founders-table/footer/index.tsx, src/components/tables/md-details-table/body/index.tsx, src/components/tables/md-details-table/footer/index.tsx, src/utils/context/mdDetails.tsx
=> Resolved warning.

src/components/common-components/select-dropdown/index.tsx, src/components/common-components/select-dropdown/selectDropdown.styled.tsx, src/components/modals/farmers-details-modal/index.tsx, src/components/tables/farmers-group-table/body/index.tsx, src/views/farmers-group/farmersGroup.styled.tsx, src/views/farmers-group/index.tsx
=> Implemented farmer group member filter and updated filter UI.

src/components/dashboard/dashboard-body/dashboard-body-top/index.tsx, src/components/dashboard/dashboard-cards/dashboard-founder-card/dashoardFounder.styled.tsx, src/components/dashboard/dashboard-cards/dashboard-founder-card/index.tsx
=> Founder card ui updated.

src/components/dashboard/dashboard-cards/dashboard-founder-card/index.tsx, src/components/tables/farmers-details-table/body/body.styled.tsx, src/components/tables/farmers-details-table/body/index.tsx, src/components/tables/farmers-details-table/header/header.styled.tsx, src/components/tables/farmers-group-table/body/body.styled.tsx, src/components/tables/farmers-group-table/body/index.tsx, src/components/tables/farmers-group-table/footer/index.tsx, src/components/tables/farmers-group-table/header/header.styled.tsx, src/components/tables/farmers-group-table/header/index.tsx, src/components/tables/farmers-group-table/index.tsx, src/components/tables/founders-table/body/body.styled.tsx, src/components/tables/founders-table/body/index.tsx, src/components/tables/founders-table/footer/index.tsx, src/components/tables/founders-table/header/header.styled.tsx, src/components/tables/founders-table/header/index.tsx, src/components/tables/md-details-table/body/body.styled.tsx, src/components/tables/md-details-table/body/index.tsx, src/components/tables/md-details-table/header/header.styled.tsx, src/components/tables/md-details-table/header/index.tsx, src/utils/context/founders.tsx, src/views/founders/index.tsx
=> Updated founder context details.

src/components/buttons/yes-or-no-buttons/YesOrNoButtons.Styled.tsx, src/components/modals/confirmation-modal/body/index.tsx, src/components/modals/confirmation-modal/index.tsx, src/components/tables/md-details-table/body/index.tsx
=> Implemented alert message with username in confirmation modal.

src/components/input-fields/autocomplete/autocomplete.styled.tsx, src/components/input-fields/autocomplete/index.tsx, src/components/modals/farmers-details-modal/page-2-fields/index.tsx, src/components/modals/farmers-group-modal/body/formField.tsx, src/components/modals/farmers-group-modal/index.tsx
=> Farmer details modal last three fields are changed as autocomplete fields.

src/components/buttons/add-profile-icon-and-button/body/uploadButton.tsx, src/components/buttons/add-profile-icon-and-button/index.tsx, src/components/dashboard/dashboard-cards/dashboard-founder-card/dashoardFounder.styled.tsx, src/components/dashboard/dashboard-cards/dashboard-founder-card/index.tsx, src/components/dashboard/dashboard-header/index.tsx, src/components/input-fields/add-profile/index.tsx, src/components/tables/farmers-details-table/body/index.tsx, src/components/tables/founders-table/body/index.tsx, src/components/tables/md-details-table/body/index.tsx, src/utils/imageCrop/imagePreview.tsx, src/views/ceo-details/CeoDetailCard.tsx, src/views/ceo-details/ceo-details.styled.tsx, src/views/farmer-detail-page/FarmerDetailsForm.tsx
=> image crop issue fixed for every profile pic upload options, profile picture edit option added to founders card in dashboard page.

src/components/common-components/select-dropdown/index.tsx, src/components/dashboard/dashboard-cards/dashboard-founder-card/index.tsx, src/components/modals/confirmation-modal/body/confirmationModal.styled.tsx, src/components/modals/confirmation-modal/body/index.tsx, src/components/modals/confirmation-modal/index.tsx, src/components/modals/decisions-modal/body/formField.tsx, src/components/modals/farmers-details-modal/index.tsx, src/components/modals/farmers-details-modal/page-1-fields/index.tsx, src/components/modals/farmers-group-modal/index.tsx, src/components/modals/md-details-modal/index.tsx, src/components/modals/new-md-details-modal/index.tsx, src/components/tables/farmers-details-table/body/index.tsx, src/components/tables/farmers-details-table/footer/index.tsx, src/components/tables/farmers-details-table/header/index.tsx, src/components/tables/farmers-group-table/body/index.tsx, src/components/tables/farmers-group-table/footer/index.tsx, src/components/tables/founders-table/body/index.tsx, src/components/tables/founders-table/footer/index.tsx, src/components/tables/md-details-table/body/body.styled.tsx, src/components/tables/md-details-table/body/index.tsx, src/components/tables/md-details-table/footer/index.tsx, src/utils/constants/index.ts, src/utils/context/farmersDetails.tsx, src/utils/context/farmersGroup.tsx, src/utils/context/founders.tsx, src/utils/context/mdDetails.tsx, src/views/farmer-detail-page/FarmerDetailsForm.tsx, src/views/farmers-group/farmersGroup.styled.tsx, src/views/tamil-share-certificate/index.tsx, src/views/tamil-share-certificate/tamil-certificate.styled.tsx
=> Update the context name change ById instead of List and Resolve the custom message in confirmation modal in tab view.

src/components/common-styles/commonStyles.styled.tsx, src/components/tables/md-details-table/body/body.styled.tsx, src/components/tables/md-details-table/body/index.tsx, src/containers/layout/header/header.styled.tsx, src/containers/layout/header/index.tsx
=> Implemented popover in header layout.

src/components/modals/decisions-modal/index.tsx, src/components/resolutions/resolutions-header/index.tsx, src/components/resolutions/resolutions-header/modal-handler.tsx, src/components/resolutions/resolutions-list/resolutionsList.styled.tsx, src/containers/layout/Layout.tsx
=> Implemented confirmation & deletion to add resolutions feature. Fixed resolutions view-all rich-text overflow bug.

src/components/common-table-page-header/index.tsx, src/components/common-table-page-header/right-section/index.tsx, src/components/resolutions/resolutions-list/index.tsx, src/components/resolutions/resolutions-tree/index.tsx, src/components/table-page-header/farmers-details-table-page-header/index.tsx, src/components/table-page-header/farmers-details-table-page-header/left-section/index.tsx, src/utils/constants/index.ts, src/utils/context/farmersDetails.tsx, src/utils/context/farmersGroup.tsx, src/utils/context/founders.tsx, src/utils/context/mdDetails.tsx
=> Changed 'ascending' & 'descending' as constant.

src/components/modals/ceo-details-modal/body/ceoDetailsModal.styled.tsx, src/components/modals/ceo-details-modal/body/formField.tsx, src/components/modals/ceo-details-modal/index.tsx, src/components/modals/type/formInputs.ts, src/containers/provider/index.tsx, src/utils/context/ceoDetails.tsx, src/views/ceo-details/CeoDetailCard.tsx, src/views/ceo-details/ceo-details.styled.tsx, src/views/ceo-details/index.tsx
=> UseContext added for Ceo details page with crud operations.

src/components/modals/notification-modal/index.tsx, src/components/tables/md-details-table/body/index.tsx, src/containers/layout/header/index.tsx, src/utils/context/authContext.tsx, src/utils/context/mdDetails.tsx, src/views/tamil-share-certificate/tamil-certificate.styled.tsx
✓Removing console logs
✓Ordering imports
✓Defining params structure
✓Removing type any with proper type
✓Removing inline styles
✓Responsiveness check
✓Proper folder and file structure
✓Defining constants for lengthy conditions
✓Use proper ternary instead of using if else
✓Declaring proper initial value to both local and global states
✓Should clean side-effects on component unmounting
✓Private keys should be in env file
✓Clear warnings and errors (rendered on browser’s console)
✓Remove unused imports and variables
✓Follow SOLID principles
✓Declare reusable components
✓Declare custom hooks
✓Put meaningful commit message (Sentence should start with capital letter and end with dot)
✓Pull before every push
✓Paste checked conditions of above in pull/push request description …
=> Implemented notification modal dynamically in context.

src/utils/context/mdDetails.tsx, src/views/md-details/index.tsx
=> checkBoxSelect function updated on mdDetails context.

src/components/input-fields/input/input.tsx, src/components/modals/decisions-modal/body/decisionsModal.styled.tsx
=> Fixed rich-text overflow bug in tab width.

src/components/custom-modal/footer/footer.styled.tsx, src/components/modals/farmers-details-modal/page-1-fields/page1Fields.styled.tsx, src/components/modals/md-details-modal/index.tsx, src/components/table-page-header/farmers-details-table-page-header/right-section/rightSection.styled.tsx, src/types/index.ts, src/utils/theme/index.tsx
=> All buttons disabled color changed, MD-details modal profile edit functionality fixed.

src/views/ceo-details/CeoDetailCard.tsx, src/views/ceo-details/ceo-details.styled.tsx
=> Ceo detail card ui updated.

src/components/modals/ceo-details-modal/body/ceoDetailsModal.styled.tsx, src/components/modals/ceo-details-modal/body/formField.tsx, src/components/modals/ceo-details-modal/index.tsx
=> CEO-datails modal changed to controlled.

src/components/admin-panel/admin-logo/index.tsx, src/components/dashboard/dashboard-cards/dashboard-founder-card/index.tsx, src/components/icons/icon-styled.tsx, src/components/modals/founders-modal/index.tsx, src/components/modals/type/formInputs.ts, src/components/tables/md-details-table/body/row.tsx, src/utils/constants/index.ts, src/utils/context/auth.tsx, src/utils/context/ceoDetails.tsx, src/utils/context/founders.tsx, src/views/admin-panel/adminPanel.styled.tsx, src/views/admin-panel/index.tsx, src/views/ceo-details/CeoDetailCard.tsx
✓Removing console logs
✓Ordering imports
✓Defining params structure
✓Removing type any with proper type
✓Removing inline styles
✓Responsiveness check
✓Proper folder and file structure
✓Defining constants for lengthy conditions
✓Use proper ternary instead of using if else
✓Declaring proper initial value to both local and global states
✓Should clean side-effects on component unmounting
✓Private keys should be in env file
✓Clear warnings and errors (rendered on browser’s console)
✓Remove unused imports and variables
✓Follow SOLID principles
✓Declare reusable components
✓Declare custom hooks
✓Put meaningful commit message (Sentence should start with capital letter and end with dot)
✓Pull before every push
✓Paste checked conditions of above in pull/push request description …
=> Date format changed in dashboard and ceo details.

src/views/farmer-detail-page/farmer-form-preview/FarmerFormPreviewLeft.tsx, src/views/farmer-detail-page/farmer-form-preview/farmer-form-preview.styled.tsx
=> Fixed scrolling issue in farmer detail form and added confirmation modal for edit modal farmer detail form.

src/components/input-fields/input/input.styled.tsx, src/components/input-fields/input/input.tsx, src/components/modals/ceo-details-modal/body/ceoDetailsModal.styled.tsx, src/components/modals/farmers-group-modal/body/farmersGroupModal.styled.tsx, src/components/modals/farmers-group-modal/body/formField.tsx, src/components/modals/farmers-group-modal/index.tsx
=> Farmer group modal changed to controlled.

src/components/custom-modal/body/body.styled.tsx, src/components/dashboard/dashboard-cards/dashboard-founder-card/dashoardFounder.styled.tsx, src/components/export-csv-data/index.tsx, src/components/modals/new-md-details-modal/body/tableData.styled.tsx, src/components/modals/new-md-details-modal/body/tableData.tsx, src/components/modals/new-md-details-modal/index.styled.tsx
=> Add Modal Scroll added and Founders card UI updated.

src/components/dashboard/dashboard-cards/dashboard-founder-card/dashoardFounder.styled.tsx, src/components/dashboard/dashboard-cards/dashboard-summary-card/dashboardSummaryCard.styled.tsx, src/containers/layout/header/header.styled.tsx, src/containers/layout/header/index.tsx, src/views/dashboard/dashboard.styled.tsx, src/views/farmer-detail-page/farmer-form-preview/farmer-form-preview.styled.tsx
=> Header ui font resize, dashboard card ui updated, farmer detail page ui updated.

src/components/tables/farmers-details-table/body/row.tsx, src/components/tables/founders-table/body/row.tsx, src/components/tables/md-details-table/body/row.tsx
=> Image Preview modal issue fixed.

src/components/modals/farmers-details-modal/index.tsx, src/components/tables/farmers-details-table/body/row.tsx, src/components/tables/farmers-details-table/header/index.tsx, src/components/tables/farmers-group-table/body/row.tsx, src/components/tables/founders-table/body/row.tsx, src/components/tables/md-details-table/body/index.tsx, src/components/tables/md-details-table/body/row.tsx, src/utils/context/farmersDetails.tsx, src/utils/context/farmersGroup.tsx, src/utils/context/founders.tsx, src/utils/context/mdDetails.tsx, src/views/farmer-detail-page/farmer-form-preview/FarmerFormPreviewLeft.tsx, src/views/farmers-details/index.tsx, src/views/farmers-group/farmersGroup.styled.tsx, src/views/md-details-page/mdDetails-form-preview/MdDetailsFormPreviewLeft.tsx, src/views/md-details/index.tsx
=> Updated Add, Edit and Delete in MD details and Farmers details page with update dynamically.

src/components/id-card/id-card-header/idCardHeader.styled.tsx, src/components/id-card/id-card-header/index.tsx, src/components/login/login-background/index.tsx, src/components/login/login-form/index.tsx, src/containers/layout/footer/index.tsx, src/containers/layout/header/index.tsx, src/utils/context/auth.tsx, src/views/admin-panel/index.tsx, src/views/farmer-detail-page/FarmerDetailsForm.tsx, src/views/farmer-detail-page/farmer-form-preview/FarmerFormPreviewLeft.tsx, src/views/farmer-detail-page/farmer-form-preview/FarmerFormPreviewRight.tsx, src/views/farmer-detail-page/farmer-form-preview/farmer-form-preview.styled.tsx, src/views/farmer-detail-page/farmerDetailPage.styled.tsx, src/views/md-details-page/MdDetailsForm.tsx, src/views/md-details-page/md-details-page.styled.tsx, src/views/md-details-page/mdDetails-form-preview/MdDetailsFormPreviewLeft.tsx, src/views/md-details-page/mdDetails-form-preview/MdDetailsFormPreviewRight.tsx, src/views/md-details-page/mdDetails-form-preview/mdDetails-form-preview.styled.tsx, src/views/resolution-certificate/resolutionCertificate.styled.tsx, src/views/resolution-certificate/resolutionPdf.tsx, src/views/tamil-share-certificate/index.tsx
=> Updated the Admin panel logo, title, RegNo and CIN no dynamically

src/utils/constants/index.ts, src/utils/hooks/query/index.tsx
=> Query structure improved.

src/components/table-page-header/farmers-details-table-page-header/right-section/index.tsx, src/components/tables/farmers-details-table/body/index.tsx
=> farmerDetails initial data and exportData updated.

src/utils/hooks/query/index.tsx
=> Implemented multiple data add functionality in useAdd() hook.

src/views/farmer-detail-page/FarmerDetailsForm.tsx, src/views/farmer-detail-page/farmer-form-preview/FarmerFormPreviewLeft.tsx, src/views/md-details-page/MdDetailsForm.tsx, src/views/md-details-page/mdDetails-form-preview/MdDetailsFormPreviewLeft.tsx
=> Fixed certificate image preview bug.

src/utils/constants/index.ts, src/views/resolution-certificate/index.tsx
=> Image removed in resolutions notification.

src/components/id-card/id-card-body/index.tsx, src/components/resolutions/resolutions-header/index.tsx, src/views/md-details-page/MdDetailsForm.tsx, src/views/md-details-page/mdDetails-form-preview/MdDetailsFormPreviewLeft.tsx
=> Implemented notification on add resolution; Changed image preivew in md.

src/components/api-loader/apiLoader.styled.tsx, src/views/ceo-details/ceo-details.styled.tsx
=> API loader & ceo details card UI corrections.

src/components/table-page-header/farmers-details-table-page-header/right-section/helper.ts, src/components/table-page-header/farmers-details-table-page-header/right-section/index.tsx, src/components/table-page-header/farmers-details-table-page-header/right-section/rightSection.styled.tsx
=>  Dynamic confirmation msg & Format err msg added on import farmers.

src/components/tables/founders-table/body/row.tsx, src/views/founders/index.tsx
=> Toast added for Founder details page.

src/components/tables/farmers-details-table/body/row.tsx
=> Edit farmer detail fixed.

src/components/modals/resolution-modal/body/formField.tsx, src/components/tables/founders-table/body/row.tsx, src/views/ceo-details/CeoDetailCard.tsx
=> Farmer group data added in resolutions modal. Added edit notification in ceo & founders.

src/components/common-components/search-bar/index.tsx
=> Implemented debouncing in searchbar.

server/db.json, server/src/mdDetails.json, src/components/tables/farmers-details-table/body/row.tsx, src/components/tables/md-details-table/body/row.tsx, src/views/farmer-detail-page/farmer-form-preview/FarmerFormPreviewLeft.tsx, src/views/md-details-page/mdDetails-form-preview/MdDetailsFormPreviewLeft.tsx
=> Updated db.json, mdDetails.json and Resolve Toaster shown in md details page.

src/components/common-components/drop-file/index.tsx, src/components/dashboard/dashboard-cards/dashboard-founder-card/index.tsx, src/components/modals/farmers-details-modal/index.tsx
=> Added click to add file functionality in import farmers. Fixed small errors and bugs.

src/containers/layout/header/header.styled.tsx, src/containers/layout/header/index.tsx
=> New navbar updated.

src/utils/constants/index.ts
=> FileToBase64 function created.

src/components/input-fields/input/input.tsx, src/components/modals/products-modal/body/formField.tsx, src/components/modals/products-modal/index.tsx, src/components/modals/type/formInputs.ts, src/components/portfolio/portfolio-header/index.tsx, src/utils/constants/index.ts
=> Products modal integrated on portfolio page.

src/components/modals/farmers-details-modal/page-1-fields/index.tsx
=> Gender issue fixed in farmerdetails modal.

src/components/common-components/drop-file/dropFile.styled.tsx, src/components/common-components/drop-file/index.tsx, src/components/custom-modal/body/body.styled.tsx, src/components/modals/import-farmers-modal/importFarmersModal.styled.tsx, src/components/modals/import-farmers-modal/index.tsx
=> Import farmers modal UI changes.

src/components/dashboard/dashboard-body/dashboard-body-top/index.tsx, src/components/dashboard/dashboard-header/index.tsx
=> Profile header changed,Dashboard header count rendered dynamically, Cultivation card hidden.

src/components/dashboard/dashboard-body/dashboard-body-top/index.tsx
=> Api loader implemented for dasboard body components.

src/components/api-loader/apiLoader.styled.tsx, src/components/dashboard/dashboard-body/dashboard-body-top/index.tsx, src/components/dashboard/dashboard-header/index.tsx
=> API loader corrections made  in dasboard.

src/views/tamil-share-certificate/index.tsx, src/views/tamil-share-certificate/tamil-certificate.styled.tsx
=> Share certificate ui updated.

src/components/tables/farmers-details-table/body/index.tsx
=> Loader issue fixed in farmerdetails page.

server/db.json, src/components/input-fields/input/input.tsx, src/components/modals/products-modal/body/formField.tsx, src/components/modals/products-modal/index.tsx, src/components/modals/type/formInputs.ts, src/components/portfolio/item-card/index.tsx, src/components/portfolio/portfolio-header/index.tsx, src/utils/constants/index.ts, src/utils/hooks/query/index.tsx
Clear warnings and errors (rendered on browser’s console) …
=> Implemented CRUD functionality on portfolio page.

src/components/tables/farmers-details-table/body/index.tsx, src/views/farmer-detail-page/FarmerDetailsForm.tsx, src/views/farmer-detail-page/farmer-form-preview/FarmerFormPreviewRight.tsx, src/views/md-details-page/MdDetailsForm.tsx, src/views/md-details-page/mdDetails-form-preview/MdDetailsFormPreviewRight.tsx, src/views/tamil-share-certificate/index.tsx, src/views/tamil-share-certificate/tamil-certificate.styled.tsx
=> Farmers details page refetching issue resolved, unique key error resolved and share certificate ui updated.

src/components/modals/products-modal/body/formField.tsx
=> MUI warning in products modal on edit fixed.

src/components/input-fields/input/input.tsx, src/components/tables/farmers-details-table/body/index.tsx
=> Text field hyphen issue fixed.

src/components/custom-tables/table/tableWrapper.styled.tsx, src/components/tables/farmers-details-table/body/body.styled.tsx, src/components/tables/farmers-details-table/body/index.tsx
=> Loader container height issue fixed.

server/db.json, src/components/modals/products-modal/body/formField.tsx, src/components/modals/products-modal/index.tsx, src/components/modals/type/formInputs.ts, src/components/portfolio/helper.ts, src/components/portfolio/item-card/index.tsx
=> Implemented last updated card shown in front in portfolio page.

src/components/dashboard/dashboard-body/dashboard-body-top/index.tsx, src/components/modals/farmers-details-modal/index.tsx, src/utils/constants/index.ts, src/utils/hooks/query/index.tsx
=> Dashboard card count updated and landAreaInCent data added.

src/components/modals/import-farmerGroup-modal/index.tsx, src/components/modals/import-farmers-modal/index.tsx, src/utils/theme/index.tsx
=> Dialogue texts & button functionality made as dynamic in import,Toast messages made as dynamic in import.

src/components/modals/farmers-details-modal/index.tsx, src/components/modals/type/formInputs.ts, src/components/tables/farmers-details-table/body/row.tsx, src/components/tables/md-details-table/body/row.tsx
farmer detail modal is submitting confirm account number to db
##What is the new behavior?
farmer detail modal will not submit confirm account number to db
##Standards
=> Confirm account number from farmer detail modal will not added to dbjson.

src/components/modals/import-farmerGroup-modal/importFarmerGroupModal.styled.tsx
=> Import farmer modal UI issue fixed.

src/components/modals/import-farmerGroup-modal/index.tsx, src/components/modals/import-farmers-modal/helper.ts, src/components/modals/import-farmers-modal/index.tsx
=> Import cache issue fixed,Mutation toast changed as dynamic for count.
